# example netlify.toml
[build]
#  command = "# no build command"
  functions = "netlify/functions"
#  publish = "public"

# [[redirects]]
#    from = "/*"
#    to = "/.netlify/functions/api/:splat"
#    status = 200
